# .github/workflows/sonarq.yml
name: "SonarQube Scan"

on:
  workflow_dispatch:

permissions:
  contents: write
  security-events: write
  pull-requests: write

env:
  CI: "true"
  SONAR_SCANNER_VERSION: "6.2.1.4610"
  SONAR_HOST_URL: "http://localhost:9000"

jobs:
  sonarqube-scan-api:
    name: SonarQube Analysis (API)
    runs-on: ubuntu-latest
    timeout-minutes: 30

    services:
      sonarqube:
        image: sonarqube:lts-community
        ports:
          - 9000:9000
        env:
          SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run SonarQube Action (API)
        uses: ./
        with:
          path: .tests/api
          project_key: e2e-api
          project_name: E2E API
          skip_pr: true

  sonarqube-scan-react:
    name: SonarQube Analysis (React)
    runs-on: ubuntu-latest
    timeout-minutes: 30

    services:
      sonarqube:
        image: sonarqube:lts-community
        ports:
          - 9000:9000
        env:
          SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run SonarQube Action (React)
        uses: ./
        with:
          path: .tests/react
          project_key: e2e-react
          project_name: E2E React
          skip_pr: true
