# .github/workflows/sonarq.yml
name: "SonarQube Scan"

on:
  workflow_dispatch:
    inputs:
      scanner_debug:
        description: "Enable SonarScanner debug (-X)"
        required: false
        default: "false"
      quality_profile:
        description: "Quality Profile name"
        required: false
        default: "Sonar way"
      quality_profile_language:
        description: "Quality Profile language"
        required: false
        default: "js"
      quality_gate:
        description: "Quality Gate name"
        required: false
        default: "Sonar way"
      sonar_token:
        description: "SonarQube token (preferred)"
        required: false
        default: ""

permissions:
  contents: write
  security-events: write
  pull-requests: write

env:
  CI: "true"
  SONAR_SCANNER_VERSION: "6.2.1.4610"
  SONAR_HOST_URL: "http://localhost:9000"

jobs:
  sonarqube-scan-api:
    name: SonarQube Analysis (API)
    runs-on: ubuntu-latest
    timeout-minutes: 30

    services:
      sonarqube:
        image: sonarqube:lts-community
        env:
          SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    env:
      SONAR_HOST_URL: "http://sonarqube:9000"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run SonarQube Action (API)
        uses: ./
        with:
          path: .tests/api
          project_key: e2e-api
          project_name: E2E API
          quality_profile: ${{ inputs.quality_profile }}
          quality_profile_language: ${{ inputs.quality_profile_language }}
          quality_gate: ${{ inputs.quality_gate }}
          sonar_token: ${{ inputs.sonar_token }}
          scanner_debug: ${{ inputs.scanner_debug }}
          skip_pr: true

  sonarqube-scan-react:
    name: SonarQube Analysis (React)
    runs-on: ubuntu-latest
    timeout-minutes: 30

    services:
      sonarqube:
        image: sonarqube:lts-community
        env:
          SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    env:
      SONAR_HOST_URL: "http://sonarqube:9000"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run SonarQube Action (React)
        uses: ./
        with:
          path: .tests/react
          project_key: e2e-react
          project_name: E2E React
          quality_profile: ${{ inputs.quality_profile }}
          quality_profile_language: ${{ inputs.quality_profile_language }}
          quality_gate: ${{ inputs.quality_gate }}
          sonar_token: ${{ inputs.sonar_token }}
          scanner_debug: ${{ inputs.scanner_debug }}
          skip_pr: true
